FinalProject/CA3/CA3/FinalProject/Controllers/AddContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FinalProject.Models;
using System.Threading.Tasks;
using System.Data.Entity.Validation;
using System.Diagnostics;

namespace FinalProject.Controllers
{
    public class AddContactController : Controller
    {
        // GET: AddContact
        public ActionResult MyContactadd()
        {
            return View();
        }


        [HttpPost]
        public ActionResult MyContactadd(Contacts addContact)
        {
            
                if (ModelState.IsValid)
                {

                    Contacts addcont = new Contacts();

                addcont.Username = Session["name"].ToString(); //ALows Session name to be used to add to new tabe acting as Primary key
                addcont.CustomersFriendNumber = addContact.CustomersFriendNumber;
                addcont.FirstName = addContact.FirstName;
              
                var db = new UserDbContext();
                    db.Contacts.Add(addcont);
                 db.SaveChanges();
            }
            return RedirectToAction("ContactDisplay", "Contacts");
                
            
           
                
            }
        }
    }

FinalProject/CA3/CA3/FinalProject/Views/AddContact/MyContactadd.cshtml
@model FinalProject.Models.Contacts
@{
    ViewBag.Title = "MyContactadd";
}

<h2>@Session["name"]  <br />
    Please enter persons name and modile number <br/>
   
    </h2>

@using (Html.BeginForm("MyContactadd", "AddContact"))
{

        <div class="editor -label">
            @Html.LabelFor(model => model.FirstName)
        </div>

        <div class="editor -label">
            @Html.ValidationMessageFor(model => model.FirstName)
            @Html.TextBoxFor(model => model.FirstName, new { @value =  @class = "form-control", placeholder = "Persons Name here", tabindex = 1 })
        </div>

        <div class="editor -label">
            @Html.ValidationMessageFor(model => model.CustomersFriendNumber)
            @Html.TextBoxFor(model => model.CustomersFriendNumber, new { @class = "form-control", placeholder = "Persons Mobile Number here", tabindex = 1 })
        </div>




<div class="form-group">
    <div>
        <button class="btn btn-primary " name="submit" type="submit" onclick="location.href='@Url.Action("ContactDisplay", "Contacts")'">
            Add Contact
        </button>
    </div>
</div>
}